package com.xiaomo.termux

import android.content.Context
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

/**
 * Manages the Termux bootstrap lifecycle: extract from assets and readiness check.
 *
 * The bootstrap zip is bundled in APK assets (no network required).
 */
class BootstrapManager(private val context: Context) {

    companion object {
        private const val TAG = "BootstrapManager"
        private const val BOOTSTRAP_ASSET = "bootstrap-aarch64.zip"
    }

    private val env = TermuxEnvironment(context)

    /**
     * Returns true if the bootstrap runtime is ready to use.
     */
    fun isReady(): Boolean = env.isReady()

    /**
     * Ensure the bootstrap is extracted from assets.
     * No-op if already ready.
     */
    suspend fun ensureReady(
        onProgress: (BootstrapProgress) -> Unit = {}
    ): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            if (isReady()) {
                onProgress(BootstrapProgress(BootstrapProgress.State.READY, message = "Runtime already installed"))
                return@withContext Result.success(Unit)
            }

            // Extract from assets
            onProgress(BootstrapProgress(BootstrapProgress.State.EXTRACTING, message = "Extracting runtime..."))
            context.assets.open(BOOTSTRAP_ASSET).use { inputStream ->
                BootstrapExtractor.extract(inputStream, env.prefixDir) { current, total ->
                    onProgress(
                        BootstrapProgress(
                            BootstrapProgress.State.EXTRACTING,
                            current = current,
                            total = total,
                            message = "Extracting files... ($current)"
                        )
                    )
                }
            }

            // Create directories
            onProgress(BootstrapProgress(BootstrapProgress.State.CONFIGURING, message = "Configuring environment..."))
            env.ensureDirectories()
            generateExecWrappers()

            // Verify
            if (!isReady()) {
                return@withContext Result.failure(RuntimeException("Bootstrap extraction completed but shell not found"))
            }

            onProgress(BootstrapProgress(BootstrapProgress.State.READY, message = "Runtime ready"))
            Result.success(Unit)
        } catch (e: Exception) {
            Log.e(TAG, "Bootstrap setup failed", e)
            onProgress(
                BootstrapProgress(
                    BootstrapProgress.State.ERROR,
                    message = "Setup failed: ${e.message}"
                )
            )
            Result.failure(e)
        }
    }

    /** Public entry point for regenerating wrappers on existing installs. */
    fun regenerateWrappers() = generateExecWrappers()

    /**
     * Generate exec-wrappers.sh: shell functions that invoke each Termux binary via
     * /system/bin/linker64, bypassing the SELinux W^X restriction on Android 10+.
     *
     * When the Termux shell (sh) tries to execute a child process (e.g. `bash`),
     * the kernel blocks it via SELinux because the binary is in the app's data dir.
     * Defining a shell function with the same name causes sh to call the function
     * instead of execve(), and the function re-launches the binary via linker64.
     */
    private fun generateExecWrappers() {
        val binDir = File(env.prefixDir, "bin")
        val wrappersFile = env.execWrappersFile
        wrappersFile.parentFile?.mkdirs()

        val prefix = env.prefixDir.absolutePath
        val sb = StringBuilder()
        sb.appendLine("# Auto-generated by BootstrapManager — do not edit")
        sb.appendLine("# Wraps Termux binaries via linker64 to bypass SELinux W^X on Android 10+")
        sb.appendLine()

        val files: List<File> = binDir.listFiles()?.toList()?.sortedBy { it.name } ?: emptyList()
        var count = 0
        files.forEach { file ->
            if (!file.isFile && !isSymlink(file)) return@forEach
            val name = file.name
            // Only allow names that are valid bash function names: [A-Za-z_][A-Za-z0-9_-]*
            // We allow hyphens (bash supports them) but skip dots, brackets, spaces, etc.
            if (!isValidBashFunctionName(name)) return@forEach
            sb.appendLine("${name}() { /system/bin/linker64 $prefix/bin/${name} \"\$@\"; }")
            count++
        }

        wrappersFile.writeText(sb.toString())
        Log.d(TAG, "Generated exec-wrappers.sh with $count / ${files.size} binaries")
    }

    private fun isSymlink(file: File): Boolean = try {
        file.canonicalPath != file.absolutePath
    } catch (_: Exception) { false }

    /**
     * Returns true if name is a valid bash function name.
     * Bash allows: letters, digits, underscores, hyphens — but must start with letter or underscore.
     * We exclude dots, brackets, spaces, and other special chars.
     */
    private fun isValidBashFunctionName(name: String): Boolean {
        if (name.isEmpty()) return false
        val first = name[0]
        if (!first.isLetter() && first != '_') return false
        return name.all { it.isLetterOrDigit() || it == '_' || it == '-' }
    }

    /**
     * Remove the bootstrap (clean uninstall).
     */
    fun removeBootstrap() {
        env.prefixDir.deleteRecursively()
        env.homeDir.deleteRecursively()
    }
}
